version: "3"
services:
  consul1:
    container_name: node1
    image: consul:1.4.4
    restart: always
    command: agent -server -bootstrap-expect=3 -node=node1 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    networks:
      - consul-net
  consul2:
    image: consul:1.4.4
    container_name: node2
    restart: always
    command: agent -server -retry-join=node1 -node=node2 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    depends_on:
      - consul1
    networks:
      - consul-net
  consul3:
    image: consul:1.4.4
    container_name: node3
    restart: always
    command: agent -server -retry-join=node1 -node=node3 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    depends_on:
      - consul1
    networks:
      - consul-net
  consul4:
    image: consul:1.4.4
    container_name: node4
    restart: always
    command: agent -retry-join=node1 -node=node4 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1 -ui
    ports:
      - 8500:8500
    depends_on:
      - consul2
      - consul3
    networks:
      - consul-net
networks:
  consul-net: